### ISSUE TITLE
there is a problem when loading the depth model

### ISSUE THREAD

**Issue by lxycopper** [KovenYu/WonderJourney#3]
![image](https://github.com/KovenYu/WonderJourney/assets/52530394/02c9c614-1ca2-4642-b286-4cec0634e071)

**Comment by lxycopper** [comment]
I follow the installation guide of MiDas and solved it

**Comment by yshen47** [comment]
Could you clarify a bit more? How do you solve this issue? thanks

**Comment by yshen47** [comment]
Solved, This post helps, https://github.com/isl-org/MiDaS/issues/255#issuecomment-1853353087
